name: Python test and lint
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  pytest:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest] # [ubuntu-latest, windows-latest, macos-latest]
        python_version: [3.11]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python_version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python_version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-ci.txt
        pip install -r requirements.txt
    - name: Lint with prospector
      run: |
        prospector --profile=prospector.yaml
    - name: Test with pytest
      run: |
        ls -la /Library/Frameworks/Python.framework/Versions/3.11/python
        file /Library/Frameworks/Python.framework/Versions/3.11/python
        ls -la /Library/Frameworks/Python.framework/Versions/3.11/
    #     pytest -vv --full-trace --cov-config=.coveragerc --cov=./ --cov-report=xml
    # - name: Report code coverage
    #   run: |
    #     codecov
