name: Python test and lint
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  pytest:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest] # windows-latest,
        python_version: [3.11]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python_version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python_version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-ci.txt
        pip install -r requirements.txt
    # - name: Lint with prospector
    #   run: |
    #     prospector --profile=prospector.yaml
    - name: Test with pytest
      run: |
        pytest -vv --cov-config=.coveragerc --cov=./ --cov-report=xml
    - name: Report code coverage
      run: |
        codecov
